import SettingsActions from './SettingsActions';
import SettingsDropdown from './SettingsDropdown';
import SettingsPanelHeader from './SettingsPanelHeader';
import SettingsToggleRow from './SettingsToggleRow';
import { formatLastSavedLabel, getOptionLabel } from '../../utils/settings/helpers';

export default function SecuritySettingsPanel({ config, draftSettings, passwordForm, securityToggleSettings, sessionTimeoutOptions, recoveryChannelOptions, onPasswordChange, onFieldChange, onToggle, onReset, onSave }) {
  const security = draftSettings.security;
  return (
    <div className="settings-panel">
      <SettingsPanelHeader config={config} lastSavedLabel={formatLastSavedLabel(draftSettings.meta.lastSavedAt)} />
      <div className="settings-grid-two"><div className="settings-section"><div className="settings-section-intro"><div><h3>Password and session rules</h3><p>Change password details and set the recovery and timeout rules used by this account.</p></div></div><div className="settings-section-body"><div className="settings-form-grid"><label className="settings-field"><span>Current Password</span><input type="password" name="currentPassword" value={passwordForm.currentPassword} onChange={onPasswordChange} placeholder="Enter current password" /></label><label className="settings-field"><span>New Password</span><input type="password" name="newPassword" value={passwordForm.newPassword} onChange={onPasswordChange} placeholder="At least 10 characters" /></label><label className="settings-field"><span>Confirm New Password</span><input type="password" name="confirmPassword" value={passwordForm.confirmPassword} onChange={onPasswordChange} placeholder="Repeat the new password" /></label><div className="settings-field"><span>Session Timeout</span><SettingsDropdown value={security.sessionTimeout} options={sessionTimeoutOptions} onChange={(value) => onFieldChange('security', 'sessionTimeout', value)} fullWidth /></div><div className="settings-field settings-field-wide"><span>Recovery Channel</span><SettingsDropdown value={security.recoveryChannel} options={recoveryChannelOptions} onChange={(value) => onFieldChange('security', 'recoveryChannel', value)} fullWidth /></div></div><p className="settings-inline-note">Use at least 10 characters, avoid reusing the current password, and rotate it whenever HR approvals are being handled by a new device.</p><div className="settings-metadata-grid"><div className="settings-metadata-card"><span className="settings-metadata-label">Password status</span><strong className="settings-metadata-value">{security.lastPasswordUpdatedLabel}</strong></div><div className="settings-metadata-card"><span className="settings-metadata-label">Recovery route</span><strong className="settings-metadata-value">{getOptionLabel(recoveryChannelOptions, security.recoveryChannel)}</strong></div><div className="settings-metadata-card"><span className="settings-metadata-label">Timeout rule</span><strong className="settings-metadata-value">{getOptionLabel(sessionTimeoutOptions, security.sessionTimeout)}</strong></div></div></div></div><div className="settings-section"><div className="settings-section-intro"><div><h3>Access protection</h3><p>Require stronger confirmation for sign-ins and sensitive record changes.</p></div></div>{securityToggleSettings.map((item) => <SettingsToggleRow key={item.key} title={item.title} description={item.description} enabled={security[item.key]} onToggle={() => onToggle('security', item.key)} />)}</div></div>
      <SettingsActions onReset={onReset} onSave={onSave} saveLabel="Save Security" />
    </div>
  );
}