const mockUsers = {
  // --- STAFF & ADMIN (Simple Data) ---
  admin_system: {
    id: "admin_system",
    name: "Elena (HR Admin)",
    role: "ADMIN",
    department: "Human Resources",
    email: "elena.admin@company.com",
  },
  staff_hr: {
    id: "staff_hr",
    name: "Marcus (HR Staff)",
    role: "HR_STAFF",
    department: "Human Resources",
    email: "marcus.hr@company.com",
  },
  supervisor_it: {
    id: "supervisor_it",
    name: "Sarah Richards (IT Supervisor)",
    role: "SUPERVISOR",
    department: "Information Technology",
    email: "sarah.supervisor@company.com",
  },

  supervisor_mktg: {
    id: "supervisor_mktg",
    name: "Anna Lopez (Marketing Supervisor)",
    role: "SUPERVISOR",
    department: "Marketing",
    email: "anna.marketing@company.com",
  },
  supervisor_hr: {
    id: "supervisor_hr",
    name: "Paolo Cruz (HR Supervisor)",
    role: "SUPERVISOR",
    department: "Human Resources",
    email: "paolo.hr@company.com",
  },

  // --- INTERNS (Detailed Personal Info matching your UI) ---
  //IT Interns
  intern_it: {
    id: "intern_it",
    role: "INTERN",
    supervisorId: "supervisor_it",
    department: "Information Technology",
    name: "Alex Santos",
    firstName: "Alex",
    lastName: "Santos",
    phone: "09123456781",
    email: "alex.it@company.com",
    dob: "05/14/2002",
    maritalStatus: "Single",
    gender: "Male",
    nationality: "Filipino",
    address: "123 Tech Street, Brgy. San Jose",
    city: "Bacoor",
    zipCode: "4102",
    university: "Polytechnic University of the Philippines (PUP iTech)",
    course: "Diploma in Information Technology",
    hours: "500 hours",
    duration: "Feb 16, 2026 - May 30, 2026",
    year: "3rd Year",
    graduation: "July 2026",
  },
  intern_it_2: {
    id: "intern_it_2",
    role: "INTERN",
    supervisorId: "supervisor_it",
    department: "Information Technology",
    name: "Nathan Dela Cruz",
    firstName: "Nathan",
    lastName: "Dela Cruz",
    phone: "09123456782",
    email: "nathan.it@company.com",
    dob: "03/18/2002",
    maritalStatus: "Single",
    gender: "Male",
    nationality: "Filipino",
    address: "Bacoor, Cavite",
    city: "Bacoor",
    zipCode: "4102",
    university: "Technological University of the Philippines",
    course: "BS Information Technology",
    hours: "500 hours",
    duration: "Feb 16, 2026 - May 30, 2026",
    year: "3rd Year",
    graduation: "July 2026",
  },
  intern_it_3: {
    id: "intern_it_3",
    role: "INTERN",
    supervisorId: "supervisor_it",
    department: "Information Technology",
    name: "Mika Torres",
    firstName: "Mika",
    lastName: "Torres",
    phone: "09123456783",
    email: "mika.it@company.com",
    dob: "09/10/2003",
    maritalStatus: "Single",
    gender: "Female",
    nationality: "Filipino",
    address: "Las Piñas City",
    city: "Las Piñas",
    zipCode: "1740",
    university: "AMA Online University",
    course: "BS Information Technology",
    hours: "600 hours",
    duration: "Feb 16, 2026 - May 30, 2026",
    year: "3rd Year",
    graduation: "August 2026",
  },
  //Marketing Interns
  intern_mktg: {
    id: "intern_mktg",
    role: "INTERN",
    supervisorId: "supervisor_mktg",
    department: "Marketing",
    name: "Chloe Mendoza",
    firstName: "Chloe",
    lastName: "Mendoza",
    phone: "09171234567",
    email: "chloe.mktg@company.com",
    dob: "08/22/2001",
    maritalStatus: "Single",
    gender: "Female",
    nationality: "Filipino",
    address: "456 Taft Avenue",
    city: "Manila",
    zipCode: "1000",
    university: "De La Salle University",
    course: "BS Business Administration",
    hours: "300 hours",
    duration: "Feb 16, 2026 - May 30, 2026",
    year: "4th Year",
    graduation: "October 2026",
  },
  intern_mktg_2: {
    id: "intern_mktg_2",
    role: "INTERN",
    supervisorId: "supervisor_mktg",
    department: "Marketing",
    name: "Bianca Ramos",
    firstName: "Bianca",
    lastName: "Ramos",
    phone: "09171234568",
    email: "bianca.mktg@company.com",
    dob: "12/01/2001",
    maritalStatus: "Single",
    gender: "Female",
    nationality: "Filipino",
    address: "Makati City",
    city: "Makati",
    zipCode: "1200",
    university: "University of Makati",
    course: "BS Marketing Management",
    hours: "300 hours",
    duration: "Feb 16, 2026 - May 30, 2026",
    year: "4th Year",
    graduation: "October 2026",
  },

  intern_mktg_3: {
    id: "intern_mktg_3",
    role: "INTERN",
    supervisorId: "supervisor_mktg",
    department: "Marketing",
    name: "Jared Lim",
    firstName: "Jared",
    lastName: "Lim",
    phone: "09171234569",
    email: "jared.mktg@company.com",
    dob: "06/25/2002",
    maritalStatus: "Single",
    gender: "Male",
    nationality: "Filipino",
    address: "Manila",
    city: "Manila",
    zipCode: "1000",
    university: "Far Eastern University",
    course: "BS Business Administration",
    hours: "300 hours",
    duration: "Feb 16, 2026 - May 30, 2026",
    year: "4th Year",
    graduation: "October 2026",
  },
  //HR Interns
  intern_hr: {
    id: "intern_hr",
    role: "INTERN",
    supervisorId: "supervisor_hr",
    department: "Human Resources",
    name: "David Reyes",
    firstName: "David",
    lastName: "Reyes",
    phone: "09209876543",
    email: "david.hr@company.com",
    dob: "11/05/2000",
    maritalStatus: "Single",
    gender: "Male",
    nationality: "Filipino",
    address: "789 Emerald Ave, Ortigas",
    city: "Pasig",
    zipCode: "1605",
    university: "University of Santo Tomas",
    course: "BS Psychology",
    hours: "400 hours",
    duration: "Feb 16, 2026 - May 30, 2026",
    year: "4th Year",
    graduation: "June 2026",
  },
  intern_hr_2: {
    id: "intern_hr_2",
    role: "INTERN",
    supervisorId: "supervisor_hr",
    department: "Human Resources",
    name: "Kyla Garcia",
    firstName: "Kyla",
    lastName: "Garcia",
    phone: "09209876544",
    email: "kyla.hr@company.com",
    dob: "02/14/2002",
    maritalStatus: "Single",
    gender: "Female",
    nationality: "Filipino",
    address: "Pasig City",
    city: "Pasig",
    zipCode: "1605",
    university: "University of Santo Tomas",
    course: "BS Psychology",
    hours: "400 hours",
    duration: "Feb 16, 2026 - May 30, 2026",
    year: "4th Year",
    graduation: "June 2026",
  },

  intern_hr_3: {
    id: "intern_hr_3",
    role: "INTERN",
    supervisorId: "supervisor_hr",
    department: "Human Resources",
    name: "Marco Villanueva",
    firstName: "Marco",
    lastName: "Villanueva",
    phone: "09209876545",
    email: "marco.hr@company.com",
    dob: "10/30/2001",
    maritalStatus: "Single",
    gender: "Male",
    nationality: "Filipino",
    address: "Taguig City",
    city: "Taguig",
    zipCode: "1630",
    university: "PUP Manila",
    course: "BS Human Resource Management",
    hours: "400 hours",
    duration: "Feb 16, 2026 - May 30, 2026",
    year: "4th Year",
    graduation: "June 2026",
  },
};

// --- CHART DATA ---
export const dummyChartDays = [
  { week: 'Week 1', values: [32, 46, 22, 40, 28, 56, 50, 74, 64, 84, 76, 99] },
  { week: 'Week 2', values: [22, 36, 52, 56, 44, 48, 62, 84, 82, 92, 90, 96] },
  { week: 'Week 3', values: [38, 60, 34, 52, 66, 76, 72, 94, 88, 80, 96, 90] },
];

export const dummyUniversities = [
  { name: 'CIT-U', value: 23, color: '#22c55e' },
  { name: 'PUP iTech', value: 30, color: '#a855f7' },
  { name: 'De La Salle University', value: 34, color: '#38bdf8' },
  { name: 'University of Santo Tomas', value: 19, color: '#f59e0b' },
  { name: 'Far Eastern University', value: 26, color: '#ef4444' },
  { name: 'University of Makati', value: 15, color: '#06b6d4' },
  { name: 'AMA Online University', value: 21, color: '#ec4899' },
  { name: 'Technological University of the Philippines', value: 24, color: '#8b5cf6' },
  { name: 'Polytechnic University of the Philippines', value: 32, color: '#14b8a6' },
  { name: 'USJR', value: 15, color: '#f97316' },
];

// --- INTERNS ---
export const dummyInterns = [
  {
    id: '345321231',
    name: 'John Doe',
    email: 'john.doe@example.com',
    firstName: 'John',
    lastName: 'Doe',
    mobileNumber: '09123456789',
    emailAddress: 'john.doe@example.com',
    dateOfBirth: '1999-03-15',
    gender: 'Male',
    university: 'CIT-U',
    program: 'BS Computer Science',
    ojtHours: '250',
    address: '123 Example St.',
    city: 'Cebu City',
    zipCode: '6000',
    department: 'IT Department',
    startDate: 'February 27, 2026',
  },
  {
    id: '987890345',
    name: 'Jane Doe',
    email: 'jane.doe@example.com',
    firstName: 'Jane',
    lastName: 'Doe',
    mobileNumber: '09123456788',
    emailAddress: 'jane.doe@example.com',
    dateOfBirth: '2000-05-02',
    gender: 'Female',
    university: 'FEU',
    program: 'BS Business Administration',
    ojtHours: '230',
    address: '456 Example Ave.',
    city: 'Manila',
    zipCode: '1000',
    department: 'HR Department',
    startDate: 'December 14, 2025',
  },
];

export const dummyInternshipOverview = [
  { label: 'CIT-U', incoming: 12, active: 8, finalizing: 3 },
  { label: 'PUP iTech', incoming: 15, active: 10, finalizing: 5 },
  { label: 'De La Salle University', incoming: 18, active: 12, finalizing: 4 },
  { label: 'University of Santo Tomas', incoming: 10, active: 7, finalizing: 2 },
  { label: 'Far Eastern University', incoming: 14, active: 9, finalizing: 3 },
  { label: 'University of Makati', incoming: 8, active: 5, finalizing: 2 },
  { label: 'AMA Online University', incoming: 11, active: 6, finalizing: 4 },
  { label: 'Technological University of the Philippines', incoming: 13, active: 8, finalizing: 3 },
  { label: 'Polytechnic University of the Philippines', incoming: 16, active: 11, finalizing: 5 },
  { label: 'USJR', incoming: 9, active: 4, finalizing: 2 },
];

// --- METRICS ---
export const dummyMetrics = [
  { label: 'Active Interns', value: '28', accent: 'bg-emerald-500', text: 'text-emerald-700' },
  { label: 'Incoming Interns', value: '15', accent: 'bg-amber-400', text: 'text-amber-700' },
  { label: 'Finalizing Internship', value: '5', accent: 'bg-rose-400', text: 'text-rose-700' },
];

// --- SYSTEM LOGS ---
export const dummyLogs = [
  {
    timestamp: '2026-04-06 | 09:12:34',
    user: 'Supervisor 1',
    role: 'Supervisor',
    action: 'Login',
    description: 'Supervisor 1 logged into the system.',
    details: 'View',
  },
  {
    timestamp: '2026-04-06 | 09:18:02',
    user: 'Intern 1',
    role: 'Intern',
    action: 'Submit Application',
    description: 'Intern 1 submitted an application.',
    details: 'View',
  },
  {
    timestamp: '2026-04-06 | 09:25:47',
    user: 'HR Staff 1',
    role: 'HR Staff',
    action: 'Update Record',
    description: 'HR Staff 1 updated intern record.',
    details: 'View',
  },
  {
    timestamp: '2026-04-06 | 09:34:21',
    user: 'Supervisor 2',
    role: 'Supervisor',
    action: 'Approve Request',
    description: 'Supervisor 2 approved a request.',
    details: 'View',
  },
];

// --- APPLICATIONS ---
export const dummyApplications = [
  {
    name: 'Darlene Robertson',
    id: '345321231',
    university: 'Cebu University',
    program: 'BS Computer Science',
    date: '2026-02-15',
    status: 'Pending',
  },
  {
    name: 'Floyd Miles',
    id: '987890345',
    university: 'FEU',
    program: 'BS Business Administration',
    date: '2026-03-02',
    status: 'Pending',
  },
  {
    name: 'Carmen Reed',
    id: '453367122',
    university: 'USJR',
    program: 'BS Information Systems',
    date: '2026-03-20',
    status: 'Pending',
  },
];

// --- DOCUMENTS ---
export const dummyDocuments = [
  { id: 1, title: 'MOA.pdf', type: 'MOA', uploaded: '2025-12-10' },
  { id: 2, title: 'Certificate of Acceptance.pdf', type: 'Acceptance', uploaded: '2025-12-12' },
  { id: 3, title: 'NDA Letter.pdf', type: 'NDA', uploaded: '2025-12-14' },
  { id: 4, title: 'ID.pdf', type: 'ID', uploaded: '2025-12-15' },
  { id: 5, title: 'Resume.pdf', type: 'Resume', uploaded: '2025-12-16' },
  { id: 6, title: 'Endorsement Letter.pdf', type: 'Endorsement', uploaded: '2025-12-18' },
];


// --- DEPARTMENTS ---
export const dummyDepartments = [
  {
    title: 'IT Department',
    count: 3,
    members: [
      { name: 'John Doe', role: 'IT Intern' },
      { name: 'Jane Doe', role: 'HR Intern' },
      { name: 'Jonathan Doe', role: 'IT Intern' },
    ],
  },
  {
    title: 'Sales Department',
    count: 3,
    members: [
      { name: 'Darrell Steward', role: 'Sr. Sales Manager' },
      { name: 'Courtney Henry', role: 'BDM' },
      { name: 'Kathryn Murphy', role: 'BDE' },
    ],
  },
  {
    title: 'Project Manager Department',
    count: 2,
    members: [
      { name: 'Ronald Richards', role: 'Sr. Project Manager' },
      { name: 'Savannah Nguyen', role: 'Project Manager' },
    ],
  },
  {
    title: 'Marketing Department',
    count: 2,
    members: [
      { name: 'Brooklyn Simmons', role: 'Sr. Marketing Manager' },
      { name: 'Kristin Watson', role: 'Marketing Coordinator' },
    ],
  },
];


// It writes the data above into the browser so the app can use it.
export const initializeMockDatabase = () => {
  localStorage.setItem("hrims_users_db", JSON.stringify(mockUsers));

  if (!localStorage.getItem("hrims_evaluations_db")) {
    localStorage.setItem("hrims_evaluations_db", JSON.stringify([]));
  }
  console.log("✅ Mock Database Updated with Profile Data!");
};
