const mockUsers = {
  // --- STAFF & ADMIN (Simple Data) ---
  admin_system: {
    id: "admin_system",
    name: "Elena (HR Admin)",
    role: "ADMIN",
    department: "Human Resources",
    email: "elena.admin@company.com",
  },
  staff_hr: {
    id: "staff_hr",
    name: "Marcus (HR Staff)",
    role: "HR_STAFF",
    department: "Human Resources",
    email: "marcus.hr@company.com",
  },
  supervisor_it: {
    id: "supervisor_it",
    name: "Sarah Richards (IT Supervisor)",
    role: "SUPERVISOR",
    department: "Information Technology",
    email: "sarah.supervisor@company.com",
  },

  supervisor_mktg: {
    id: "supervisor_mktg",
    name: "Anna Lopez (Marketing Supervisor)",
    role: "SUPERVISOR",
    department: "Marketing",
    email: "anna.marketing@company.com",
  },
  supervisor_hr: {
    id: "supervisor_hr",
    name: "Paolo Cruz (HR Supervisor)",
    role: "SUPERVISOR",
    department: "Human Resources",
    email: "paolo.hr@company.com",
  },

  // --- INTERNS (Detailed Personal Info matching your UI) ---
  //IT Interns
  intern_it: {
    id: "intern_it",
    role: "INTERN",
    supervisorId: "supervisor_it",
    department: "Information Technology",
    name: "Alex Santos",
    firstName: "Alex",
    lastName: "Santos",
    phone: "09123456781",
    email: "alex.it@company.com",
    dob: "05/14/2002",
    maritalStatus: "Single",
    gender: "Male",
    nationality: "Filipino",
    address: "123 Tech Street, Brgy. San Jose",
    city: "Bacoor",
    zipCode: "4102",
    university: "Polytechnic University of the Philippines (PUP iTech)",
    course: "Diploma in Information Technology",
    hours: "500 hours",
    duration: "Feb 16, 2026 - May 30, 2026",
    year: "3rd Year",
    graduation: "July 2026",
  },
  intern_it_2: {
    id: "intern_it_2",
    role: "INTERN",
    supervisorId: "supervisor_it",
    department: "Information Technology",
    name: "Nathan Dela Cruz",
    firstName: "Nathan",
    lastName: "Dela Cruz",
    phone: "09123456782",
    email: "nathan.it@company.com",
    dob: "03/18/2002",
    maritalStatus: "Single",
    gender: "Male",
    nationality: "Filipino",
    address: "Bacoor, Cavite",
    city: "Bacoor",
    zipCode: "4102",
    university: "Technological University of the Philippines",
    course: "BS Information Technology",
    hours: "500 hours",
    duration: "Feb 16, 2026 - May 30, 2026",
    year: "3rd Year",
    graduation: "July 2026",
  },
  intern_it_3: {
    id: "intern_it_3",
    role: "INTERN",
    supervisorId: "supervisor_it",
    department: "Information Technology",
    name: "Mika Torres",
    firstName: "Mika",
    lastName: "Torres",
    phone: "09123456783",
    email: "mika.it@company.com",
    dob: "09/10/2003",
    maritalStatus: "Single",
    gender: "Female",
    nationality: "Filipino",
    address: "Las Piñas City",
    city: "Las Piñas",
    zipCode: "1740",
    university: "AMA Online University",
    course: "BS Information Technology",
    hours: "600 hours",
    duration: "Feb 16, 2026 - May 30, 2026",
    year: "3rd Year",
    graduation: "August 2026",
  },
  //Marketing Interns
  intern_mktg: {
    id: "intern_mktg",
    role: "INTERN",
    supervisorId: "supervisor_mktg",
    department: "Marketing",
    name: "Chloe Mendoza",
    firstName: "Chloe",
    lastName: "Mendoza",
    phone: "09171234567",
    email: "chloe.mktg@company.com",
    dob: "08/22/2001",
    maritalStatus: "Single",
    gender: "Female",
    nationality: "Filipino",
    address: "456 Taft Avenue",
    city: "Manila",
    zipCode: "1000",
    university: "De La Salle University",
    course: "BS Business Administration",
    hours: "300 hours",
    duration: "Feb 16, 2026 - May 30, 2026",
    year: "4th Year",
    graduation: "October 2026",
  },
  intern_mktg_2: {
    id: "intern_mktg_2",
    role: "INTERN",
    supervisorId: "supervisor_mktg",
    department: "Marketing",
    name: "Bianca Ramos",
    firstName: "Bianca",
    lastName: "Ramos",
    phone: "09171234568",
    email: "bianca.mktg@company.com",
    dob: "12/01/2001",
    maritalStatus: "Single",
    gender: "Female",
    nationality: "Filipino",
    address: "Makati City",
    city: "Makati",
    zipCode: "1200",
    university: "University of Makati",
    course: "BS Marketing Management",
    hours: "300 hours",
    duration: "Feb 16, 2026 - May 30, 2026",
    year: "4th Year",
    graduation: "October 2026",
  },

  intern_mktg_3: {
    id: "intern_mktg_3",
    role: "INTERN",
    supervisorId: "supervisor_mktg",
    department: "Marketing",
    name: "Jared Lim",
    firstName: "Jared",
    lastName: "Lim",
    phone: "09171234569",
    email: "jared.mktg@company.com",
    dob: "06/25/2002",
    maritalStatus: "Single",
    gender: "Male",
    nationality: "Filipino",
    address: "Manila",
    city: "Manila",
    zipCode: "1000",
    university: "Far Eastern University",
    course: "BS Business Administration",
    hours: "300 hours",
    duration: "Feb 16, 2026 - May 30, 2026",
    year: "4th Year",
    graduation: "October 2026",
  },
  //HR Interns
  intern_hr: {
    id: "intern_hr",
    role: "INTERN",
    supervisorId: "supervisor_hr",
    department: "Human Resources",
    name: "David Reyes",
    firstName: "David",
    lastName: "Reyes",
    phone: "09209876543",
    email: "david.hr@company.com",
    dob: "11/05/2000",
    maritalStatus: "Single",
    gender: "Male",
    nationality: "Filipino",
    address: "789 Emerald Ave, Ortigas",
    city: "Pasig",
    zipCode: "1605",
    university: "University of Santo Tomas",
    course: "BS Psychology",
    hours: "400 hours",
    duration: "Feb 16, 2026 - May 30, 2026",
    year: "4th Year",
    graduation: "June 2026",
  },
  intern_hr_2: {
    id: "intern_hr_2",
    role: "INTERN",
    supervisorId: "supervisor_hr",
    department: "Human Resources",
    name: "Kyla Garcia",
    firstName: "Kyla",
    lastName: "Garcia",
    phone: "09209876544",
    email: "kyla.hr@company.com",
    dob: "02/14/2002",
    maritalStatus: "Single",
    gender: "Female",
    nationality: "Filipino",
    address: "Pasig City",
    city: "Pasig",
    zipCode: "1605",
    university: "University of Santo Tomas",
    course: "BS Psychology",
    hours: "400 hours",
    duration: "Feb 16, 2026 - May 30, 2026",
    year: "4th Year",
    graduation: "June 2026",
  },

  intern_hr_3: {
    id: "intern_hr_3",
    role: "INTERN",
    supervisorId: "supervisor_hr",
    department: "Human Resources",
    name: "Marco Villanueva",
    firstName: "Marco",
    lastName: "Villanueva",
    phone: "09209876545",
    email: "marco.hr@company.com",
    dob: "10/30/2001",
    maritalStatus: "Single",
    gender: "Male",
    nationality: "Filipino",
    address: "Taguig City",
    city: "Taguig",
    zipCode: "1630",
    university: "PUP Manila",
    course: "BS Human Resource Management",
    hours: "400 hours",
    duration: "Feb 16, 2026 - May 30, 2026",
    year: "4th Year",
    graduation: "June 2026",
  },
};

export const dummyDepartments = [
  {
    title: 'IT Department',
    count: 3,
    members: [
      { name: 'John Doe', role: 'IT Intern' },
      { name: 'Jane Doe', role: 'HR Intern' },
      { name: 'Jonathan Doe', role: 'IT Intern' },
    ],
  },
  {
    title: 'Sales Department',
    count: 3,
    members: [
      { name: 'Darrell Steward', role: 'Sr. Sales Manager' },
      { name: 'Courtney Henry', role: 'BDM' },
      { name: 'Kathryn Murphy', role: 'BDE' },
    ],
  },
  {
    title: 'Project Manager Department',
    count: 2,
    members: [
      { name: 'Ronald Richards', role: 'Sr. Project Manager' },
      { name: 'Savannah Nguyen', role: 'Project Manager' },
    ],
  },
  {
    title: 'Marketing Department',
    count: 2,
    members: [
      { name: 'Brooklyn Simmons', role: 'Sr. Marketing Manager' },
      { name: 'Kristin Watson', role: 'Marketing Coordinator' },
    ],
  },
];

// It writes the data above into the browser so the app can use it.
export const initializeMockDatabase = () => {
  if (!localStorage.getItem("hrims_users_db")) {
    localStorage.setItem("hrims_users_db", JSON.stringify(mockUsers));
    console.log("✅ Mock Database Initialized!");
  } else {
    console.log("ℹ️ Mock Database already exists.");
  }

  if (!localStorage.getItem("hrims_evaluations_db")) {
    localStorage.setItem("hrims_evaluations_db", JSON.stringify([]));
  }
  console.log("✅ Mock Database Updated with Profile Data!");
};


// --- SYSTEM LOGS ---
export const dummyLogs = [
  {
    timestamp: '2026-04-06 | 09:12:34',
    user: 'Supervisor 1',
    role: 'Supervisor',
    action: 'Login',
    description: 'Supervisor 1 logged into the system.',
    details: 'View',
  },
  {
    timestamp: '2026-04-06 | 09:18:02',
    user: 'Intern 1',
    role: 'Intern',
    action: 'Submit Application',
    description: 'Intern 1 submitted an application.',
    details: 'View',
  },
  {
    timestamp: '2026-04-06 | 09:25:47',
    user: 'HR Staff 1',
    role: 'HR Staff',
    action: 'Update Record',
    description: 'HR Staff 1 updated intern record.',
    details: 'View',
  },
  {
    timestamp: '2026-04-06 | 09:34:21',
    user: 'Supervisor 2',
    role: 'Supervisor',
    action: 'Approve Request',
    description: 'Supervisor 2 approved a request.',
    details: 'View',
  },
];



export const hrAdminDashboardData = {
  greeting: {
    name: '[Name]',
    message: 'Good Morning',
    dateLabel: 'Today:',
    dateValue: '28th March 2023',
  },
  quickActions: [
    { id: 'add_intern', label: 'Add Intern' },
    { id: 'generate_report', label: 'Generate Report' },
  ],
  metrics: [
    { title: 'Total Interns', value: '470', trend: '12%', trendType: 'up' },
    { title: 'Completed Interns', value: '1050', trend: '3%', trendType: 'up' },
    { title: 'Active Interns', value: '470', trend: '8%', trendType: 'down' },
    { title: 'Partner Universities', value: '12', trend: '12%', trendType: 'up' },
  ],
  recentActivity: [
    { label: 'New application submitted', description: 'Description', color: 'bg-sky-300' },
    { label: 'Supervisor evaluation completed', description: 'Description', color: 'bg-emerald-400' },
    { label: 'New DTR submitted', description: 'Description', color: 'bg-sky-300' },
    { label: 'MOA uploaded', description: 'Description', color: 'bg-sky-300' },
  ],
  attendanceOverview: {
    filterLabel: 'Today',
    days: [
      { day: 'Mon', levels: [58, 88, 98] },
      { day: 'Tue', levels: [58, 78, 98] },
      { day: 'Web', levels: [45, 74, 98] },
      { day: 'Thu', levels: [58, 88, 98] },
      { day: 'Fri', levels: [75, 82, 98] },
      { day: 'Sat', levels: [42, 75, 98] },
      { day: 'Sun', levels: [42, 85, 98] },
    ],
  },
};